// Command archdoc generates the project architecture overview from Go package
// metadata. It keeps the diagram aligned with the packages compiled by Go.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const defaultOutputPath = "docs/architecture.md"

type listedModule struct {
	Path string
	Dir  string
	Main bool
}

type listedPackage struct {
	ImportPath string
	Name       string
	Doc        string
	Dir        string
	Imports    []string
	Module     *listedModule
}

type packageGroup struct {
	ID    string
	Title string
}

var packageGroups = []packageGroup{
	{ID: "commands", Title: "Commands"},
	{ID: "transport", Title: "HTTP transport"},
	{ID: "application", Title: "Application services"},
	{ID: "domain", Title: "Domain"},
	{ID: "infrastructure", Title: "Infrastructure"},
	{ID: "client", Title: "Client"},
}

func main() {
	if err := run(context.Background(), os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(argContext context.Context, args []string, stdout io.Writer, stderr io.Writer) error {
	flags := flag.NewFlagSet("archdoc", flag.ContinueOnError)
	flags.SetOutput(stderr)

	outputPath := flags.String(
		"output",
		defaultOutputPath,
		"path of the generated Markdown document",
	)
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return errors.New("archdoc does not accept positional arguments")
	}

	packages, err := loadPackages(argContext)
	if err != nil {
		return err
	}

	document, err := generateDocument(packages)
	if err != nil {
		return err
	}
	if err := os.WriteFile(*outputPath, document, 0o644); err != nil {
		return fmt.Errorf("write architecture document: %w", err)
	}

	fmt.Fprintf(stdout, "Generated %s from %d Go packages.\n", *outputPath, len(packages))

	return nil
}

func loadPackages(argContext context.Context) ([]listedPackage, error) {
	command := exec.CommandContext(argContext, "go", "list", "-json", "./...")
	output, err := command.Output()
	if err != nil {
		var exitError *exec.ExitError
		if errors.As(err, &exitError) {
			return nil, fmt.Errorf(
				"list Go packages: %w: %s",
				err,
				strings.TrimSpace(string(exitError.Stderr)),
			)
		}

		return nil, fmt.Errorf("list Go packages: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(output))
	var packages []listedPackage
	for {
		var pkg listedPackage
		if err := decoder.Decode(&pkg); errors.Is(err, io.EOF) {
			break
		} else if err != nil {
			return nil, fmt.Errorf("decode Go package metadata: %w", err)
		}
		if isProductPackage(pkg) {
			packages = append(packages, pkg)
		}
	}

	if len(packages) == 0 {
		return nil, errors.New("no product packages found")
	}

	return packages, nil
}

func isProductPackage(pkg listedPackage) bool {
	if pkg.Module == nil || !pkg.Module.Main {
		return false
	}

	relativePath, err := filepath.Rel(pkg.Module.Dir, pkg.Dir)
	if err != nil {
		return false
	}
	relativePath = filepath.ToSlash(relativePath)

	return relativePath != "tools/archdoc" && !strings.HasPrefix(relativePath, "tools/")
}

func generateDocument(packages []listedPackage) ([]byte, error) {
	packages = append([]listedPackage(nil), packages...)
	sort.Slice(packages, func(first int, second int) bool {
		return packages[first].ImportPath < packages[second].ImportPath
	})

	modulePath, moduleDir, err := mainModule(packages)
	if err != nil {
		return nil, err
	}

	packageIDs := make(map[string]string, len(packages))
	for index, pkg := range packages {
		packageIDs[pkg.ImportPath] = fmt.Sprintf("package%d", index)
	}

	var document strings.Builder
	document.WriteString("<!-- Code generated by go run ./tools/archdoc; DO NOT EDIT. -->\n\n")
	document.WriteString("# Architecture overview\n\n")
	document.WriteString("This page describes the production packages in `")
	document.WriteString(modulePath)
	document.WriteString("`. It is generated from the package metadata returned by `go list -json ./...`.\n\n")
	document.WriteString("Regenerate it after changing package boundaries or imports:\n\n")
	document.WriteString("```bash\n")
	document.WriteString("go run ./tools/archdoc -output docs/architecture.md\n")
	document.WriteString("```\n\n")
	document.WriteString("## Related documentation\n\n")
	document.WriteString("- [Database structure](database.md)\n\n")
	document.WriteString("## Package dependencies\n\n")
	document.WriteString("An arrow from package A to package B means that A imports B. External and standard-library packages are intentionally omitted.\n\n")
	document.WriteString("```mermaid\nflowchart LR\n")

	for _, group := range packageGroups {
		var groupPackages []listedPackage
		for _, pkg := range packages {
			if groupForPackage(modulePath, pkg.ImportPath) == group.ID {
				groupPackages = append(groupPackages, pkg)
			}
		}
		if len(groupPackages) == 0 {
			continue
		}

		fmt.Fprintf(&document, "  subgraph %s[\"%s\"]\n", group.ID, group.Title)
		for _, pkg := range groupPackages {
			fmt.Fprintf(
				&document,
				"    %s[\"%s\"]\n",
				packageIDs[pkg.ImportPath],
				strings.TrimPrefix(pkg.ImportPath, modulePath+"/"),
			)
		}
		document.WriteString("  end\n")
	}

	for _, pkg := range packages {
		imports := append([]string(nil), pkg.Imports...)
		sort.Strings(imports)
		for _, importedPath := range imports {
			importedID, exists := packageIDs[importedPath]
			if !exists {
				continue
			}
			fmt.Fprintf(
				&document,
				"  %s --> %s\n",
				packageIDs[pkg.ImportPath],
				importedID,
			)
		}
	}
	document.WriteString("```\n\n")
	document.WriteString("## Modules\n\n")
	document.WriteString("| Package | Layer | Package documentation |\n")
	document.WriteString("| --- | --- | --- |\n")
	for _, pkg := range packages {
		relativePath, err := filepath.Rel(moduleDir, pkg.Dir)
		if err != nil {
			return nil, fmt.Errorf("resolve package path %q: %w", pkg.ImportPath, err)
		}
		relativePath = filepath.ToSlash(relativePath)
		fmt.Fprintf(
			&document,
			"| [`%s`](../%s) | %s | %s |\n",
			strings.TrimPrefix(pkg.ImportPath, modulePath+"/"),
			relativePath,
			groupTitle(groupForPackage(modulePath, pkg.ImportPath)),
			packageDocumentation(pkg.Doc),
		)
	}

	return []byte(document.String()), nil
}

func mainModule(packages []listedPackage) (string, string, error) {
	for _, pkg := range packages {
		if pkg.Module != nil && pkg.Module.Main {
			return pkg.Module.Path, pkg.Module.Dir, nil
		}
	}

	return "", "", errors.New("main module metadata is missing")
}

func groupForPackage(modulePath string, importPath string) string {
	relativePath := strings.TrimPrefix(importPath, modulePath+"/")
	switch {
	case strings.HasPrefix(relativePath, "cmd/"):
		return "commands"
	case relativePath == "internal/api":
		return "transport"
	case strings.HasPrefix(relativePath, "internal/application/"):
		return "application"
	case strings.HasPrefix(relativePath, "internal/storage/"):
		return "infrastructure"
	case relativePath == "internal/client":
		return "client"
	default:
		return "domain"
	}
}

func groupTitle(groupID string) string {
	for _, group := range packageGroups {
		if group.ID == groupID {
			return group.Title
		}
	}

	return "Other"
}

func packageDocumentation(documentation string) string {
	documentation = strings.Join(strings.Fields(documentation), " ")
	if documentation == "" {
		return "Not documented yet."
	}
	if index := strings.Index(documentation, "."); index >= 0 {
		documentation = documentation[:index+1]
	}

	return strings.ReplaceAll(documentation, "|", "\\|")
}
